CREATE TABLE CIDADE (
CODIGO INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(128) NOT NULL,
ESTADO ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'PA', 'PB', 'RE', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
ALTERADO TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE BARBEIRO (
CODIGO BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
CODIGO_BARBEARIA BIGINT(20) NOT NULL,
CODIGO_CIDADE INT(20) NOT NULL,
NOME VARCHAR(128) NOT NULL,
CPF VARCHAR(20) NOT NULL,
FOTO VARCHAR(200),
DATA_NASCIMENTO TIMESTAMP NOT NULL,
CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
ALTERADO TIMESTAMP NOT NULL DEFAULT NOW(),
CONSTRAINT FK_BARBEIRO_CIDADE FOREIGN KEY (CODIGO_CIDADE) REFERENCES CIDADE(CODIGO)
);

CREATE TABLE ENDERECO (
CODIGO INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
CODIGO_CIDADE INT(20) NOT NULL,
ENDERECO VARCHAR(128) NOT NULL,
NUMERO INT(5) NOT NULL,
CEP VARCHAR(12),
CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
ALTERADO TIMESTAMP NOT NULL DEFAULT NOW(),
CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (CODIGO_CIDADE) REFERENCES CIDADE(CODIGO)
);