CREATE TABLE CIDADE (
	CODIGO INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(128) NOT NULL,
	ESTADO ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'PA', 'PB', 'RE', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
	CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
	ALTERADO TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE BARBEIRO (
	CODIGO BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CODIGO_BARBEARIA BIGINT(20) NOT NULL,
	CODIGO_CIDADE INT(20) NOT NULL,
	NOME VARCHAR(128) NOT NULL,
    RG VARCHAR(20) NOT NULL,
	CPF VARCHAR(20) NOT NULL,
    TELEFONE INT(20),
	CELULAR INT(20) NOT NULL,
    FOTO VARCHAR(200),
	DATA_NASCIMENTO DATE NOT NULL,
	CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
	ALTERADO TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT FK_BARBEIRO_CIDADE FOREIGN KEY (CODIGO_CIDADE) REFERENCES CIDADE(CODIGO)
);

CREATE TABLE ENDERECO (
	CODIGO INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CODIGO_CIDADE INT(20) NOT NULL,
	ENDERECO VARCHAR(128) NOT NULL,
	NUMERO INT(5) NOT NULL,
	CEP VARCHAR(12),
	CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
	ALTERADO TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (CODIGO_CIDADE) REFERENCES CIDADE(CODIGO)
);

CREATE TABLE BARBEARIA (
	CODIGO BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(60) NOT NULL,
	DESCRICAO VARCHAR(128) NOT NULL DEFAULT "",
    CODIGO_ENDERECO INT NOT NULL,
	HORARIO_ABERTURA TIME,
	HORARIO_FECHAMENTO TIME,
	CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
	ALTERADO TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_BARBEARIA_ENDERECO FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO(CODIGO)
);

CREATE TABLE CLIENTE (
	CODIGO BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CIDADE INT(20) NOT NULL,
	NOME VARCHAR(128) NOT NULL,
    RG VARCHAR(20) NOT NULL,
	CPF VARCHAR(20) NOT NULL,
	TELEFONE INT(20),
	CELULAR INT(20) NOT NULL,
	FOTO VARCHAR(200),
	DATA_NASCIMENTO TIMESTAMP NOT NULL,
	CADASTRO TIMESTAMP NOT NULL DEFAULT NOW(),
	ALTERADO TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY (CODIGO_CIDADE) REFERENCES CIDADE(CODIGO)
);

CREATE TABLE SERVICO (
	CODIGO INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODIGO_BARBEARIA BIGINT(20) NOT NULL,
    DESCRICAO VARCHAR(60) NOT NULL,
    PRECO DECIMAL(9,2) NOT NULL,
    CADASTRO TIMESTAMP NOT NULL,
    ALTERADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_SERVICO_BARBEARIA FOREIGN KEY (CODIGO_BARBEARIA) REFERENCES BARBEARIA(CODIGO)
);

CREATE TABLE HORARIO (
	CODIGO INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(50),
    HORA TIME,
    CADASTRO TIMESTAMP NOT NULL DEFAULT current_timestamp,
    ALTERADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP    
);

CREATE TABLE HORARIO_MARCADO (
	CODIGO BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODIGO_HORARIO INT(20) NOT NULL,
    CODIGO_BARBEIRO BIGINT(20) NOT NULL,
    CODIGO_CLIENTE BIGINT(20) NOT NULL,
    DIA DATE DEFAULT NULL,
    CADASTRO TIMESTAMP NOT NULL DEFAULT current_timestamp,
    ALTERADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_HORARIO_MARCADO_HORARIA FOREIGN KEY (CODIGO_HORARIO) REFERENCES HORARIO(CODIGO),
    CONSTRAINT FK_HORARIO_MARCADO_BARBEIRO FOREIGN KEY (CODIGO_BARBEIRO) REFERENCES BARBEIRO(CODIGO),
    CONSTRAINT FK_HORARIO_MARCADO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO)
);
